### ISSUE TITLE
CATransform3D Bug - M33 Property Pointing to M34

### ISSUE THREAD

**Issue by springlo** [AntonTheDev/FlightAnimator#13]
in CATransform3D 
`springs[SpringAnimationKey.M33] = self.m33.interpolationSprings((toValue as! CATransform3D).m34,
                                                                            initialVelocity : startingVelocity.x,
                                                                            angularFrequency : angularFrequency,
                                                                            dampingRatio : dampingRatio)[SpringAnimationKey.CGFloat]
`
m34 must change to m33

**Comment by AntonTheDev** [comment]
I'm on it :)

**Comment by AntonTheDev** [comment]
Fixed it accordingly, need Internet for connection to retag it for release :)

**Comment by AntonTheDev** [comment]
Fixed tag, and pushed while ridding in an Uber :)
