### ISSUE TITLE
Bezier path?

### ISSUE THREAD

**Issue by ghost** [AntonTheDev/FlightAnimator#16]
Does FlightAnimator support Bezier path?

**Comment by AntonTheDev** [comment]
@Domsware Oh boy!! This one has been bugging me forever....... If you can help in figuring out how to reverse engineer a bezier path into a set of data points, I'd love to implement this.

**Comment by ghost** [comment]
@AntonTheDev Hum... FlighrAnimator is a great job: I don't think I can help you in this way.

**Comment by AntonTheDev** [comment]
Appreciate it man, I'll definitely keep looking in to the bezier path. If I can somehow figure out how to get the data points from a CGPath, I'll try to make it happen, it wouldn't too hard to iterate over a matrix. But so far unfortunately I have had no luck :/

**Comment by ghost** [comment]
In fact my current need is not focused on bezier: bezier is only a way to achieve this. What I want is a two step process: 1/ build an animation programmatically by "glueing" several animations and 2/ launch this animation later.

Maybe I am not clear enough! The final animation is programmatically build and it required several steps.

**Comment by AntonTheDev** [comment]
@Domsware I think that was the intent for **triggerOnProgres/**/**triggerOnValueProgress** methods. You can trigger another animation on the same view or a completely different view by nesting them within the declaration. 

Documentation can he found here 

https://github.com/AntonTheDev/FlightAnimator#time-progress-trigger

**Comment by ghost** [comment]
Ok, thank you.
I'll create a new issue in the incoming minute about animation caching.

**Comment by AntonTheDev** [comment]
@Domsware I just fixed a bug in 0.9.5, with an issue that didn't allow you to chain an animation on the same view that triggered the animation. It was using the same cache key, which caused issue, it now generates a UUID for each animation.

**Comment by ghost** [comment]
Ok, I'll give a try today!

**Comment by AntonTheDev** [comment]
@Domsware  Cheers :) Appreciate all the feed back!  

P.S. I just pushed FlightLayout, it allows you to calculate a destination frame with ease too, you can then parse it into a center point and a size to animate, a nifty little UIView Extension :)

https://github.com/AntonTheDev/FlightLayout
