### ISSUE TITLE
Are cache animations tied to a view?

### ISSUE THREAD

**Issue by ghost** [AntonTheDev/FlightAnimator#17]
Is cached animation not tied to any view? Not view dependent?

In my idea an animation is created once an then reuse when needed on any view.

**Comment by ghost** [comment]
Ok, I understand: there is a mismatch between the documentation and the code.

On FA version 0.9.5, `registerAnimation` doesn't exist but `cacheAnimation`. So code should be updated as follow:

```` swift
struct AnimationKeys {
	static let CenterStateFrameAnimation  = "CenterStateFrameAnimation"
}
...

cacheAnimation(forKey : AnimationKeys.CenterStateFrameAnimation) { (animator) in
      animator.bounds(newBounds).duration(0.5).easing(.OutCubic)
      animator.position(newPositon).duration(0.5).easing(.OutCubic)
})
````

**Comment by AntonTheDev** [comment]
@Domsware I update the framework to remove the legacy documentation, and updated the method name within the framework to the example below. The animations are stored against a single view, which you can register during initialization, and trigger them using the key associated with that animation. They are released after the view is deallocated. Just bumped the framework to 0.9.6

```
struct AnimationKeys {
	static let CenterStateFrameAnimation  = "CenterStateFrameAnimation"
}
...

view.registerAnimation(forKey : AnimationKeys.CenterStateFrameAnimation) { (animator) in
      animator.bounds(newBounds).duration(0.5).easing(.OutCubic)
      animator.position(newPositon).duration(0.5).easing(.OutCubic)
})
```

**Comment by AntonTheDev** [comment]
@Domsware I am closing this issue :)
