### ISSUE TITLE
Demo app doesn't build out of the box

### ISSUE THREAD

**Issue by ZevEisenberg** [AntonTheDev/FlightAnimator#18]
Steps to reproduce:

1. Install CocoaPods 1.2.1
1. Run `pod try FlightAnimator`
1. Xcode opens with the project.
1. Click "Build and Run"

Expected results: project runs

Actual results:

```
/var/folders/j_/86_9xkgj0pqc0q2h5xx_9lt40000gn/T/CocoaPods/Try/FlightAnimator/FlightAnimator-Demo/FlightAnimator-Demo/ViewController.swift:2:8: error: no such module 'FlightAnimator'
import FlightAnimator
       ^
```

**Comment by AntonTheDev** [comment]
It's a good day, just fixed that up. That was my bad, I was importing the framework referencing a local build to test access control. Should be fixed now :)
